apiVersion: skaffold/v2alpha3
kind: config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-315817
  artifacts:
    - image: asia.gcr.io/ticketing-dev-315817/auth #hosts image in asia gcloud repo
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' #take all .ts files from src
            dest: . #where to sync inside running container