name: deploy-orders

on: 
  push: 
    branches:
      - master
    paths:
      - 'orders/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t sanyamjain221/orders . #build an image
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin #we have added these two secrets inside repo already
        env: #tell github to treat them as env variables
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sanyamjain221/orders #push image to dockerhub
      - uses: digitalocean/action-doctl@v2 #use cloud provider action here
        with:
          token: 'digitalocean_access_token'
      - run: doctl kubernetes cluster kubeconfig save ticketing #ticketing is cluster name
      - run: kubectl rollout restart deployment orders-depl #restarts our deployment (orders-depl is deployment name inside configuration file)
      
