name: deploy-manifests

on: 
  push: 
    branches:
      - master
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2 #use cloud provider action here
        with:
          token: 'digitalocean_access_token'
      - run: doctl kubernetes cluster kubeconfig save ticketing #ticketing is cluster name
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod #applies all config files to our cluster
